# Generated by Django 4.1.2 on 2022-12-08 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsae', '0025_remove_avis_time_created_alter_avis_adherant_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
